modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Lykrast/MysticalWildlife/issues"

[[mods]]
modId="mysticalwildlife"
version="${version}"
displayName="Mystical Wildlife"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-wildlife"
logoFile="logo.png"
authors="Lykrast, MCVinnyq"
description='''
Adds several imaginary animals to populate your worlds and make the wildlife a bit more varied and interesting, especially from biome to biome.
'''

[[dependencies.mysticalwildlife]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticalwildlife]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"